[project]
name = "media115"
version = "0.1.0"
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "httpx[socks]",
    "fastapi",
    "uvicorn",
    "lxml",
    "click",
    "pyyaml",
]

[project.scripts]
"115-media" = "media115.cli:main"

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = ["pytest", "pytest-xdist"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-n auto"
